package com.app.enums;

public enum StreamServiceType {
    YANDEX_MUSIC_LINK,
    SPOTIFY_MUSIC_LINK,
    APPLE_MUSIC_LINK,
    YOUTUBE_MUSIC_LINK,
    GOOGLE_PLAY_MUSIC_LINK,
    SOUNDCLOUD_MUSIC_LINK,
    SHAZAM_MUSIC_LINK,
    INVALID_LINK
}
